# default config.yml

# The host name and port to listen on
# hostname - ip address or hostname to allow connections from, default is "0.0.0.0" 
#            (any). "localhost" would prevent remote clients from connecting.
hostname: 
port: 4711

# Determine whether locations are RELATIVE to the spawn point (default like pi) or ABSOLUTE
location: RELATIVE

# Determine whether hit events are triggered by LEFT clicks, RIGHT clicks or BOTH
hitclick: RIGHT

#  SEVERE (ошибка)
#  WARNING (предупреждение)
#  INFO (информационное сообщение)
#  CONFIG
#  FINE (сообщение об успешной операции)
#  FINER
#  FINEST
loglevel: FINEST

# The URL to the homepage of your server
server_url: 'http://www.civilizationcraft.net/'
server_url_description: 'CivCraft Homepage'

# ============================== Language Configuration ====================================
# If you wish to localize CivilizationCraft, run the server once to generate a default_lang.yml file
# Then rename the file. For example "ru_lang.yml" and then translate the strings to Russian.
# Update this config line below to match the name of your translated file.
localization_file: "en_US"